# Generated by Django 2.0.2 on 2018-03-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userAdderss',
            new_name='userAddress',
        ),
    ]
